// AUTO-GENERATED — do not edit by hand.
// Coarse equirectangular land/water mask (256×128) derived from a
// public-domain NASA "land_shallow_topo" image, downsampled and thresholded to
// 1 bit/cell. Row 0 = +90° lat (north), column 0 = -180° lon. Used to place
// the hero globe's dots on land only. Land ratio ≈ 33%.

export const MASK_W = 256;
export const MASK_H = 128;

const PACKED =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4P8HSP8XAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBYf/T//z8PAAAAAAAAIAAACAAAAAAAAAAAAAAAAAAA8P8H/P///wEAAD8BAAAAAAB4AAAAAAAAAAAAAAAAAAAJ+PD/////AQAAnAEAAAAAAIAAAAAAAAAAAAAAAAAcBDj/wP////8HAAAAAAAAgAEAAO8AAAAAAAAAAAAAAPAf0n8AgP///wMAAAAAAAAHAID//wEAfAcAAAAAAAAAHwD3BAAA///fAQAAAAAAwAEA8P//AQMQAAAAAAAAAID3nx//AQD///8AAAAAAADgAO7/////H/gAAAABAAMAAPA/OP8fAPj/vwAAAAAIAMCA///////f/88BgADw/x+/4380uP8A9v8/AAAA4H8AAJj//////////7s+A/z///9/eP6//gH8/wEAAAD8/4/x/+////////////8/8P////v//z/QD/x/AAAAAP7/H////////////////zj+////+f//C/4E/A8APwAA//zx////////////////AOT///////998AP4BwAPAIB///v//////////////38A/v//////fzCAAfADAAAA8J///////////////////wD+//////8fAB4A4AEAAAD4j5/9////////////f/QHAPoX8P///x8AfgIAAAAAAPA/8P////////////8/DAAAAAuA//+/PwD/BwAAAAA4MA/+9///////////DwAGAACABQD/////Af4PAAAAAHBAjv////////////8HgA8AADAAAP7///8H/h8AAAAAeMCD/////////////wGABwAAAAAA+v///z//ewAAAADOwPv/////////3///KYADAAAAAADw////f///AAAAAO75//////////////8/gAEAAAAAAOD//////38AAAAA4P3/////////f////y+AAAAAAAAA4P//////hAAAAAAA////////////////LwAAAAAAAACA/v//+f/DAwAAAOD///////////////8vAAAAAAAAAAD//3/w/wMDAAAAwP///////////////ycAAAAAAAAAAP///6//HwAAAACA//+f+f//////////AwQAAAAAAAAA////2/8CAAAAAID/+Q/48/////////8hAAAAAAAAAID////7PwAAAAAA/gPzD+Dj////////f3AAAAAAAAAAAP////8/AAAAAAD8Q86P4+f///////8PAAAAAAAAAAAA/////wcAAAAAAPxAyPj/x////////wcYAAAAAAAAAAD/////BwAAAAAA/gCI+b/H//////8/BhgAAAAAAAAAAP7///8DAAAAAAB8AIb4/8///////38MDgAAAAAAAAAA/P///wMAAAAAAAD/AAD+////////PwwOAAAAAAAAAAD8////AQAAAAAA+P8AAP7///////8/5AEAAAAAAAAAAOD///8AAAAAAAD8/wEA/v///////39wAAAAAAAAAAAA4P//PwAAAAAAAP7/xwP/////////fyAAAAAAAAAAAABA//87AAAAAAAA/v////////////9/AAAAAAAAAAAAAID/D2AAAAAAAAD///9///P//////38AAAAAAAAAAAAAwP4HYAAAAAAAwP/////+5///////PwAAAAAAAAAAAAAA/QdAAAAAAADA//////0f/v////8fAAAAAAAAAAAAAAD5BwABAAAAAOD//////Z8A/////18AAAAAAAAAAAAAAPAHQAAAAAAA8P/////5/wP/////JwAAAAAAAAAAAAAA4AegAQAAAADw//////P/A/7///8BAAAAAAAAAAAAAADghwMGAAAAAPD/////9/8D+D/8TwAAAAAAAAAAAAAAAMCPA3AAAAAA8P/////n/wHwD/xnAAAAAAAAAAAAAAAAAP8BAAAAAADw/////89/APAH+A9AAAAAAAAAAAAAAAAA/AEAAAAAAPD/////3x8A8APoH2AAAAAAAAAAAAAAAADAHwAAAAAA8P/////fDwDgAcA/YAAAAAAAAAAAAAAAAAAfAAAAAADw/////78BAOABwD8AAAAAAAAAAAAAAAAAABwQAAAAAPD/////fwAA4AFAPiAAAAAAAAAAAAAAAAAAGPwdAAAA4P//////DwDAAUAcgAAAAAAAAAAAAAAAAACw/R8AAADA//////8PAMADQASAAgAAAAAAAAAAAAAAAED/PwAAAID//////w8AAAJAAIADAAAAAAAAAAAAAAAAAP5/AAAAAP/7////BwAAAoABCAEAAAAAAAAAAAAAAAAA/v8HAAAATPD///8DAAAAsAMMAAAAAAAAAAAAAAAAAAD+/w8AAAAAgP///wMAAABgAw8AAAAAAAAAAAAAAAAAAP//HwAAAACA////AAAAAMCCDwAAAAAAAAAAAAAAAACA//8/AAAAAID//38AAAAA4OPvAQAAAAAAAAAAAAAAAAD//38AAAAAwP9/PwAAAACAx49AAQAAAAAAAAAAAAAAgP///wEAAACA/38fAAAAAADPZ1AGAQAAAAAAAAAAAACA////DwAAAAD//w8AAAAAAI9m3D8AAAAAAAAAAAAAAMD///8/AAAAAP//DwAAAAAABCAA/gAAAAAAAAAAAAAAgP///38AAAAA/v8PAAAAAAAYAID8QQAAAAAAAAAAAACA////fwAAAAD+/w8AAAAAAOABIP4BAAAAAAAAAAAAAAD///9/AAAAAP7/DwAAAAAAAAADMAMEAAAAAAAAAAAAAP7//z8AAAAA/P8eAAAAAAAAAAAABAAAAAAAAAAAAAAA/v//HwAAAAD8/x4AAAAAAAAA4CEAAAAAAAAAAAAAAAD8//8PAAAAAP7/HwwAAAAAAADwIQAAAAAAAAAAAAAAAPz//w8AAAAA/v8fDAAAAAAAAP5xAAAAAAAAAAAAAAAA+P//DwAAAAD//58HAAAAAAAA//MAAAAAAAAAAAAAAADg//8PAAAAAP//hwcAAAAAAID//wAAQAAAAAAAAAAAAMD//w8AAAAA/v+DBwAAAAAAwP//AAAAAAAAAAAAAAAAwP//BwAAAAD+/4EHAAAAAADw//8DAAAAAAAAAAAAAADA//8HAAAAAPz/gQMAAAAAAP7//wcAAAAAAAAAAAAAAMD//wAAAAAA/P+BAwAAAAAA/v//BwAAAAAAAAAAAAAAwP9/AAAAAAD8/4EDAAAAAAD+//8PAAAAAAAAAAAAAADA/z8AAAAAAPh/AAAAAAAAAP///x8AAAAAAAAAAAAAAOD/PwAAAAAA+H8AAAAAAAAA/v//HwAAAAAAAAAAAAAA4P8fAAAAAADwfwAAAAAAAAD+//8fAAAAAAAAAAAAAADg/w8AAAAAAPA/AAAAAAAAAPz//x8AAAAAAAAAAAAAAOD/DwAAAAAA4B8AAAAAAAAA/P//HwAAAAAAAAAAAAAA4P8HAAAAAADgDwAAAAAAAAD8gP8PAAAAAAAAAAAAAADg/wMAAAAAAEAAAAAAAAAAABwA/QcAAAAAAAAAAAAAAPD/AAAAAAAAAAAAAAAAAAAAAAD6BwAIAAAAAAAAAAAA8P8AAAAAAAAAAAAAAAAAAAAAAPgHABAAAAAAAAAAAADwPwAAAAAAAAAAAAAAAAAAAAAAgAEAcAAAAAAAAAAAAPAPAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAA+AMAAAAAAAAAAAAAAAAAAAAAAIABABwAAAAAAAAAAAD4BwAAAAAAAAAAAAAAAAAAAAAAgAEABgAAAAAAAAAAAPgDAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAwAEAAAAAAAAAAAD4AQAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAPwBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAD4AADgL8DB4g8AAAAAAAAAAAAAAAAAPwAAAAAAAAAAgP//A/7/AAD/vwAAAAAAAAAAAAAAAOAfAAAAAAAAAOCB///P//8K8P///wEAAAAAAAAAAAAA9B8AAAAA/v+z//////////79////fwAAAAAAAACADwDwPwAAAPD//37//f//+///////////AAAAAABAAoD/3/8fAAAA3v///////z/e/////////x8AAAAA4P//W/z//x8AAMD/////////////////////CwAAAOD//////////wMA8Of///////////////////8DAADA/////v//f//3AQjH/////////////////////8d////zf/7////vTsyPy/v///////////////////////8h//3///////9/BvgO8Pb//////////////////0/+/wIA+P8f/P///38AMMDz/f///////////////////wEAAAAAAAD8/////wH8g////v//////////////////PRAAWAAAAJfz//8Pf/////////////////////////8POP8BA/yf/////wf4//////////////////////////8//////////////////////////////////////////////////////////////////////////////////////w==";

// Decode the base64 bit-packed mask once into a Uint8Array of bytes.
const BITS = (() => {
  const bin = typeof atob !== "undefined"
    ? atob(PACKED)
    : Buffer.from(PACKED, "base64").toString("binary");
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
})();

/**
 * Returns true if the given geographic coordinate falls on land.
 * @param lonDeg longitude in [-180, 180]
 * @param latDeg latitude in [-90, 90]
 */
export function isLand(lonDeg: number, latDeg: number): boolean {
  let x = Math.floor(((lonDeg + 180) / 360) * MASK_W);
  let y = Math.floor(((90 - latDeg) / 180) * MASK_H);
  if (x < 0) x = 0; else if (x >= MASK_W) x = MASK_W - 1;
  if (y < 0) y = 0; else if (y >= MASK_H) y = MASK_H - 1;
  const idx = y * MASK_W + x;
  return (BITS[idx >> 3] & (1 << (idx & 7))) !== 0;
}
